### PR TITLE
[0.5.x] Adds Inertia 2.0 support

### PR DESCRIPTION
**Pull request by timacdonald**

### CODE REVIEW

**Comment by mreduar** [comment]
@timacdonald Apart from the version bumb, do you think there are any other major changes to be made?

**Comment by timacdonald** [comment]
I was not able to find any issues when upgrading.

As far as I can tell there are no breaking changes.

**Comment by joelstein** [comment]
Inertia v2 is out! 🎉

**Comment by onlime** [comment]
I've been testing `laravel-precognition-vue-inertia@0.5.13` for a while now on Inertia `2.0.0-beta.2` + `2.0.0-beta.3`, now also on final `2.0.0` and it always worked flawlessly. Please release it.

**Comment by john-dent** [comment]
:shipit:

**Comment by joelstein** [comment]
Thanks!

**Pull request merged**
